# fly.toml app configuration file generated for psi-ai on 2023-10-19T18:54:52+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "psi-ai"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[env]
  DATASTORE_ID = 12345
  DATASOURCE_ID = 12345
  AGENT_ID = 12345
  QDRANT_API_URL = "http:/localhost:6333"